;/*FB_PKG_DELIM*/

__d("CometSaveAddToCollectionDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4975193105909709"}),null);
__d("CometSaveAddToCollectionDialogQuery$Parameters",["CometSaveAddToCollectionDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometSaveAddToCollectionDialogQuery_facebookRelayOperation"),metadata:{},name:"CometSaveAddToCollectionDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("useCollectionThumbnailImage_collection.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[{kind:"RootArgument",name:"scale"}],kind:"Fragment",metadata:null,name:"useCollectionThumbnailImage_collection",selections:[{alias:null,args:[{kind:"Literal",name:"height",value:48},{kind:"Variable",name:"scale",variableName:"scale"},{kind:"Literal",name:"width",value:48}],concreteType:"Image",kind:"LinkedField",name:"collection_thumbnail_image",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"uri",storageKey:null}],storageKey:null}],type:"ContentCollection",abstractKey:"__isContentCollection"};e.exports=a}),null);
__d("CometSaveCollectionInitial.react",["fbt","TetraText.react","react","stylex"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j,k=j||d("react"),l={imageSize36:{height:"xc9qbxq",width:"x14qfxbe",$$css:!0},imageSize48:{height:"xsdox4t",width:"x1useyqa",$$css:!0},initialRoot:{alignItems:"x6s0dn4",backgroundColor:"xwnonoy",borderTopStartRadius:"x1lq5wgf",borderTopEndRadius:"xgqcy7u",borderBottomEndRadius:"x30kzoy",borderBottomStartRadius:"x9jhf4c",boxShadow:"xlg9a9y",display:"x78zum5",justifyContent:"xl56j7k",position:"x1n2onr6",$$css:!0}};function a(a){var b=a.name;a=a.size;a=a===void 0?36:a;var d="headlineEmphasized4";switch(a){case 36:d="headlineEmphasized2";break;case 48:d="headlineEmphasized1";break}return k.jsx("div",{className:(i||(i=c("stylex")))(a===36&&l.imageSize36,a===48&&l.imageSize48,l.initialRoot),children:b!=null&&b.length>0&&k.jsx(c("TetraText.react"),{color:"primaryOnMedia",type:d,children:h._("__JHASH__-GqwRJxuBGC__JHASH__",[h._param("Collection first character",String.fromCodePoint(b.codePointAt(0)))])})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometSaveAddToCollectionDialog.entrypoint",["CometSaveAddToCollectionDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.collectionItemID;var b=1;(a==null||a==="")&&(b=0);return{queries:{dialogViewerQueryRef:{parameters:c("CometSaveAddToCollectionDialogQuery$Parameters"),variables:{allSavesLimit:b,collectionItemID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometSaveAddToCollectionDialog.react").__setRef("CometSaveAddToCollectionDialog.entrypoint")};g["default"]=a}),98);
__d("CometSaveCollectionConstants",[],(function(a,b,c,d,e,f){"use strict";a=36;b=48;c=5;d=["CONTRIBUTOR"];e="CONTRIBUTOR";var g=40,h="2581223601936986",i=16;f.COLLECTION_AVATAR_SIZE_MEDIUM=a;f.COLLECTION_AVATAR_SIZE_LARGE=b;f.COLLECTION_FACEPILE_CONTRIBUTORS_LIMIT=c;f.COLLECTION_FACEPILE_CONTRIBUTORS_ROLES=d;f.COLLECTION_CONTRIBUTOR_ROLE_DEFAULT=e;f.COLLECTION_NAME_MAX_LENGTH=g;f.MANUAL_COLLECTION_TEMPLATE_ID=h;f.PRIVACY_ICON_SIZE=i}),66);
__d("useAddToCollectionFlow",["CometSaveAddToCollectionDialog.entrypoint","react","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useCallback,j=b.useRef;function a(a){var b=j(null);a=c("useCometEntryPointDialog")(c("CometSaveAddToCollectionDialog.entrypoint"),{collectionItemID:a});var d=a[0];a=i(function(a,b){d(a,b)},[d]);return[a,b]}g["default"]=a}),98);
__d("useCollectionThumbnailImage",["CometRelay","useCollectionThumbnailImage_collection.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h!==void 0?h:h=b("useCollectionThumbnailImage_collection.graphql");function a(a){a=(a=d("CometRelay").useFragment(i,a))==null?void 0:a.collection_thumbnail_image;return a?{uri:a.uri}:null}g["default"]=a}),98);
__d("CometSaveSavableMoreActionsMenuQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4468883469884975"}),null);