;/*FB_PKG_DELIM*/

__d("GroupsCometRequestToParticipateFromChatDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6532309186888303"}),null);
__d("GroupsCometRequestToParticipateFromChatDialogQuery$Parameters",["GroupsCometRequestToParticipateFromChatDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometRequestToParticipateFromChatDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometRequestToParticipateFromChatDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometCancelForumParticipationRequestDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5236204216436092"}),null);
__d("GroupsCometCancelForumParticipationRequestDialogQuery$Parameters",["GroupsCometCancelForumParticipationRequestDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometCancelForumParticipationRequestDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometCancelForumParticipationRequestDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("useNuxOnce_nux.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useNuxOnce_nux",selections:[{alias:null,args:null,kind:"ScalarField",name:"nux_id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"should_show",storageKey:null}],type:"DefaultNUX",abstractKey:null};e.exports=a}),null);
__d("GroupsCometRequestToParticipateFromChatDialog.entrypoint",["GroupsCometRequestToParticipateFromChatDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{myQueryReference:{parameters:c("GroupsCometRequestToParticipateFromChatDialogQuery$Parameters"),variables:{groupID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometRequestToParticipateFromChatDialog.react").__setRef("GroupsCometRequestToParticipateFromChatDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometRequestToParticipateFromChatDialogFbts",["fbt"],(function(a,b,c,d,e,f,g,h){"use strict";a=h._("__JHASH__MkzA14JUv0k__JHASH__");g.RequestToParticipateDialogTitle=a}),98);
__d("useGroupsCometRequestToPartcipateFromChatEntryPointDialog",["CometCardedDialogLoadingStateLegacy.react","GroupsCometRequestToParticipateFromChatDialog.entrypoint","GroupsCometRequestToParticipateFromChatDialogFbts","react","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){a=a.groupID;return c("useCometEntryPointDialog")(c("GroupsCometRequestToParticipateFromChatDialog.entrypoint"),{groupID:a},void 0,function(a){return i.jsx(c("CometCardedDialogLoadingStateLegacy.react"),{onClose:a,title:d("GroupsCometRequestToParticipateFromChatDialogFbts").RequestToParticipateDialogTitle,withCloseButton:!0})})}g["default"]=a}),98);
__d("GroupsCometCancelForumParticipationRequestDialog.entrypoint",["GroupsCometCancelForumParticipationRequestDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{myQueryReference:{parameters:c("GroupsCometCancelForumParticipationRequestDialogQuery$Parameters"),variables:{groupID:a}}}}},root:c("JSResourceForInteraction")("GroupsCometCancelForumParticipationRequestDialog.react").__setRef("GroupsCometCancelForumParticipationRequestDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometCancelForumParticipationRequestDialogFbts",["fbt"],(function(a,b,c,d,e,f,g,h){"use strict";a=h._("__JHASH__CmHi9B7qvSB__JHASH__");g.CancelForumParticipationRequestDialogTitle=a}),98);
__d("useGroupsCometCancelForumParticipationRequestEntryPointDialog",["CometCardedDialogLoadingStateLegacy.react","GroupsCometCancelForumParticipationRequestDialog.entrypoint","GroupsCometCancelForumParticipationRequestDialogFbts","react","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){a=a.groupID;return c("useCometEntryPointDialog")(c("GroupsCometCancelForumParticipationRequestDialog.entrypoint"),{groupID:a},void 0,function(a){return i.jsx(c("CometCardedDialogLoadingStateLegacy.react"),{onClose:a,title:d("GroupsCometCancelForumParticipationRequestDialogFbts").CancelForumParticipationRequestDialogTitle,withCloseButton:!0})})}g["default"]=a}),98);
__d("isGroupNameMatchingKeywords",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){if(b==="")return!0;b=g(b).split(" ").reduce(function(a,b){return a+"(?=.*"+b+")"},"");return RegExp(b,"gi").test(a)}function g(a){return a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}f["default"]=a}),66);
__d("useNuxOnce",["CometLogImpressionFBNuxMutation","RelayHooks","react","useNuxOnce_nux.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i;c=i||d("react");var j=c.useCallback,k=c.useRef;function a(a){var c=d("RelayHooks").useRelayEnvironment();a=d("RelayHooks").useFragment(h!==void 0?h:h=b("useNuxOnce_nux.graphql"),a);var e=a==null?void 0:a.nux_id,f=(a==null?void 0:a.should_show)===!0&&e!=null,g=k(!1);a=j(function(){!g.current&&e!=null&&f&&(g.current=!0,d("CometLogImpressionFBNuxMutation").commit(c,e))},[c,e,f,g]);return[f,a]}g["default"]=a}),98);
__d("MWPUseRunOnFocusOrFirstVisible",["react","useMWPWatchFolderFocusChanges","useVisibilityObserver"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useCallback,j=b.useRef;function a(a){var b=j(!1),d=j(!1),e=i(function(){d.current===!1&&a(),d.current=!0,b.current=!0},[a]);e=c("useVisibilityObserver")({onHidden:function(){b.current=!1},onVisible:e});c("useMWPWatchFolderFocusChanges")(a,b);return e}g.useRunOnFocusOrFirstVisible=a}),98);
__d("MWPUseMarkFolderSeen",["MWPUseRunOnFocusOrFirstVisible","useMWPMarkSeen"],(function(a,b,c,d,e,f,g){"use strict";function a(a){a=c("useMWPMarkSeen")(a);return d("MWPUseRunOnFocusOrFirstVisible").useRunOnFocusOrFirstVisible(a)}g.useMarkFolderSeenOnFocusChange=a}),98);
__d("CometSearchEntityScope",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({GROUP:"group",PAGE:"page",USER:"user"});c=a;f["default"]=c}),66);
__d("XCometGroupScopedSearchControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/{idorvanity}/search/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometPageScopedSearchControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/page/{idorvanity}/search/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometUserScopedSearchControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/profile/{idorvanity}/search/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("useCometEntityScopedSearchRouteUrlBuilder",["XCometGroupScopedSearchControllerRouteBuilder","XCometPageScopedSearchControllerRouteBuilder","XCometUserScopedSearchControllerRouteBuilder","react","useSearchCometResultsCommonRouteParamBuilder"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useCallback;function j(a){switch(a){case"group":return c("XCometGroupScopedSearchControllerRouteBuilder");case"page":return c("XCometPageScopedSearchControllerRouteBuilder");case"user":return c("XCometUserScopedSearchControllerRouteBuilder")}}function a(a){var b=a.entityID,d=a.entityType;a=babelHelpers.objectWithoutPropertiesLoose(a,["entityID","entityType"]);var e=c("useSearchCometResultsCommonRouteParamBuilder")(a);return i(function(a){return j(d).buildURL(babelHelpers["extends"]({idorvanity:b},e.build(a)))},[e,b,d])}g["default"]=a}),98);
__d("GroupsEntityScopedCometTypeaheadDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4958745114174592"}),null);