;/*FB_PKG_DELIM*/

__d("FBReelsEntityDialogImplQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7030410840368888"}),null);
__d("FBReelsEntityDialogImplQuery$Parameters",["FBReelsEntityDialogImplQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("FBReelsEntityDialogImplQuery_facebookRelayOperation"),metadata:{},name:"FBReelsEntityDialogImplQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("FBReelsFeedbackBarPlaceholder.react",["CometColumn.react","CometColumnItem.react","CometGlimmer.react","react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react"),k={feedbackBarContainer:{marginEnd:"xbpkl22",paddingBottom:"xdvlbce",paddingStart:"x1u72gb5",width:"xygnafs",zIndex:"x1vjfegm",$$css:!0},feedbackButton:{borderTopStartRadius:"x14yjl9h",borderTopEndRadius:"xudhj91",borderBottomEndRadius:"x18nykt9",borderBottomStartRadius:"xww2gxu",height:"x1vqgdyp",width:"x100vrsf",$$css:!0},noPadding:{paddingStart:"x1swvt13",$$css:!0}};function a(a){a=a.noPadding;return j.jsx("div",{className:(h||(h=c("stylex")))([k.feedbackBarContainer,a===!0?k.noPadding:null]),children:j.jsxs(c("CometColumn.react"),{spacing:12,children:[j.jsx(c("CometColumnItem.react"),{paddingTop:0,paddingVertical:20,children:j.jsx(c("CometGlimmer.react"),{index:0,xstyle:k.feedbackButton})}),j.jsx(c("CometColumnItem.react"),{paddingTop:0,paddingVertical:20,children:j.jsx(c("CometGlimmer.react"),{index:0,xstyle:k.feedbackButton})}),j.jsx(c("CometColumnItem.react"),{paddingTop:0,paddingVertical:20,children:j.jsx(c("CometGlimmer.react"),{index:0,xstyle:k.feedbackButton})})]})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("FBReelsFullScreenContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b={isFullScreen:!0,setFullScreen:function(a){}};c=a.createContext(b);g["default"]=c}),98);
__d("useFBReelsViewerBaseDimensions",["CometAppNavigationConstants","CometRouteRenderType","FBReelsConstants","FBReelsFullScreenContext","react","useCometWindowSize"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext,j=36,k=200,l=320;function a(){var a=i(c("FBReelsFullScreenContext"));a=a.isFullScreen;var b=d("CometRouteRenderType").useIsPushView(),e=c("useCometWindowSize")(),f=e.innerHeight;e=e.innerWidth;a=!a;var g=e<=d("FBReelsConstants").VIEWER_WIDTH_THRESHOLD;f=f;a&&g&&(f=Math.round(f/2));b?!a&&g&&(f-=d("CometAppNavigationConstants").HEADER_HEIGHT):(!a||!g)&&(f-=d("CometAppNavigationConstants").HEADER_HEIGHT);f=Math.max(f,d("FBReelsConstants").MIN_VIEWER_HEIGHT);f-=j;b=Math.round(f*d("FBReelsConstants").MEDIA_ASPECT_RATIO);var h=b+k,m=e-l;a?!g&&h>m&&(b=m-k,f=Math.round(b/d("FBReelsConstants").MEDIA_ASPECT_RATIO)):h>e&&(b=e-k,f=Math.round(b/d("FBReelsConstants").MEDIA_ASPECT_RATIO));return{height:f,width:b}}g["default"]=a}),98);
__d("ReelsVideoLoadingView.react",["CometHeroHoldTrigger.react","FBReelsConstants","ReelsCardHeaderGlimmer.react","react","useFBReelsViewerBaseDimensions"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){a=a.reason;var b=babelHelpers["extends"]({},c("useFBReelsViewerBaseDimensions")(),{minHeight:d("FBReelsConstants").MIN_VIEWER_HEIGHT,minWidth:d("FBReelsConstants").MIN_VIEWER_HEIGHT*9/16});a=a!=null?"("+a+")":"";a="Reels View Loading "+a;return i.jsx("div",{className:"x6s0dn4 x78zum5 xt7dq6l xl56j7k x1n2onr6 xh8yej3",children:i.jsx("div",{className:"xjbqb8w x1lq5wgf xgqcy7u x30kzoy x9jhf4c x78zum5 x1q0g3np x6ikm8r x10wlt62 x1n2onr6 x1k90msu x6o7n8i x9lcvmn x1m6m0jg",style:b,children:i.jsx("div",{className:"x1cy8zhl x132nzbk x78zum5 xdt5ytf x5yr21d x1nhvcw1 x1n2onr6 xh8yej3",children:i.jsxs("div",{className:"xod5an3 x1d52u69 x14vqqas xktia5q",children:[i.jsx(c("CometHeroHoldTrigger.react"),{description:a,hold:!0}),i.jsx(c("ReelsCardHeaderGlimmer.react"),{})]})})})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("FBReelsMuteContextDefaultValue",[],(function(a,b,c,d,e,f){"use strict";a={isMuted:!1,setMute:function(a){}};f["default"]=a}),66);
__d("FBReelsMuteContext",["FBReelsMuteContextDefaultValue","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(c("FBReelsMuteContextDefaultValue"));g["default"]=b}),98);
__d("useFBReelsProcessRoute",["CometRouteParams","useRoutePassthroughProps","uuidv4"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=d("CometRouteParams").useRouteParams(),b=c("useRoutePassthroughProps")()||{},e=typeof a.video_id==="string"?a.video_id:"",f=typeof b.trackingString==="string"?b.trackingString:"",g=typeof b.rootVideoTrackingKey==="string"?b.rootVideoTrackingKey:"",h=typeof b.rootVideoID==="string"?b.rootVideoID:"",i=typeof a.group_id==="string"?a.group_id:null,j="";typeof a.s==="string"?j=a.s:typeof b.s==="string"&&(j=b.s);a=typeof b.sessionID==="string"?b.sessionID:c("uuidv4")();var k=!Boolean(b.showComments),l=typeof b.isMuted==="boolean"?b.isMuted:null,m=typeof b.index==="number"?b.index:null,n=b.paginationFragment;b=b.paginationFragmentKey;return{aggregationPageNodeIndex:m,aggregationPaginationFragment:n,aggregationPaginationFragmentKey:b,groupID:i,isFullScreen:k,isMutedFromPreviousRoute:l,rootVideoID:h,rootVideoTrackingKey:g,source:j,trackingString:f,videoID:e,viewerSessionID:a}}g["default"]=a}),98);
__d("useFBReelsMute",["CometRouteRenderType","react","useFBReelsProcessRoute"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useState;function a(){var a=d("CometRouteRenderType").useIsPushView(),b=c("useFBReelsProcessRoute")();b=b.isMutedFromPreviousRoute;b=i(typeof b==="boolean"?b:!a);a=b[0];var e=b[1];b=function(a){e(a)};return[a,b]}g["default"]=a}),98);
__d("FBReelsMuteContextProvider",["FBReelsMuteContext","FBReelsMuteContextDefaultValue","react","useFBReelsMute"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useContext,k=b.useMemo;function l(a){a=a.children;var b=c("useFBReelsMute")(),d=b[0],e=b[1];b=k(function(){return{isMuted:d,setMute:e}},[d,e]);return i.jsx(c("FBReelsMuteContext").Provider,{value:b,children:a})}l.displayName=l.name+" [from "+f.id+"]";function a(a){var b=a.children,d=a.shouldUseParentContext,e=j(c("FBReelsMuteContext"));return d===!0&&e!==c("FBReelsMuteContextDefaultValue")?b:i.jsx(l,babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("ReelsProcessingRendererQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5224715374298351"}),null);/*FB_PKG_DELIM*/
__d("GroupsCometMembershipQuestionsEntrypointDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6794719533913259"}),null);
__d("GroupsCometMembershipQuestionsEntrypointDialogQuery$Parameters",["GroupsCometMembershipQuestionsEntrypointDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometMembershipQuestionsEntrypointDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometMembershipQuestionsEntrypointDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometParticipationQuestionsDialogFbts_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometParticipationQuestionsDialogFbts_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6699862463413592"}),null);
__d("GroupsCometParticipationQuestionsDialogQuery$Parameters",["GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometParticipationQuestionsDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometParticipationQuestionsDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometFeatureDetailViewDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6140494279389752"}),null);
__d("GroupsCometFeatureDetailViewDialogQuery$Parameters",["GroupsCometFeatureDetailViewDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometFeatureDetailViewDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometFeatureDetailViewDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("addLocalGroupFeedInlineMessage",["CometRelay","cometUniqueID","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";function h(a,b,d){a=a.get(b);if(a==null){c("recoverableViolation")("Group Feed Inline Message Updater: Could not find group edge in store","groups_comet");return}b=a.getLinkedRecords("local_feed_inline_messages")||[];a.setLinkedRecords([].concat(b,[d]),"local_feed_inline_messages")}function a(a,b,e){d("CometRelay").commitLocalUpdate(a,function(a){var d="client:LocalGroupFeedVideoInlineMessage:"+c("cometUniqueID")(),f=a.create(d,"LocalGroupFeedVideoInlineMessage");f.setValue(String(d),"id");f.setValue(String(b),"group_id");f.setValue(String(e),"message");h(a,b,f)})}function b(a,b,e){d("CometRelay").commitLocalUpdate(a,function(a){var d=a.get(b);if(d==null){c("recoverableViolation")("Group Feed Inline Message Updater: Could not find group edge in store","groups_comet");return}var f=d.getLinkedRecords("local_feed_inline_messages")||[];f=f.filter(function(a){return(a==null?void 0:a.getDataID())!==e});a["delete"](e);d.setLinkedRecords(f,"local_feed_inline_messages")})}g.addLocalVideoFeedMessage=a;g.removeLocalFeedMessage=b}),98);
__d("GroupsCometMembershipQuestionsDialog.entrypoint",["GroupsCometMembershipQuestionsEntrypointDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometMembershipQuestionsEntrypointDialogQuery$Parameters"),variables:{group_id:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometMembershipQuestionsEntrypointDialog.react").__setRef("GroupsCometMembershipQuestionsDialog.entrypoint")};b=a;g["default"]=b}),98);
__d("GroupsCometParticipationQuestionsDialog.entrypoint",["GroupsCometParticipationQuestionsDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometParticipationQuestionsDialogQuery$Parameters"),variables:{groupID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometParticipationQuestionsDialog.react").__setRef("GroupsCometParticipationQuestionsDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometParticipationQuestionsDialogFbts",["fbt","GroupsCometParticipationQuestionsDialogFbts_group.graphql"],(function(a,b,c,d,e,f,g,h){"use strict";var i;i!==void 0?i:i=b("GroupsCometParticipationQuestionsDialogFbts_group.graphql");a=h._("__JHASH__-t3p-Co1t7r__JHASH__");c=h._("__JHASH__50ywu1Q1jWX__JHASH__");g.participationQuestionsDialogTitle=a;g.participationReviewDialogTitle=c}),98);
__d("useGroupsCometParticipationQuestionsEntryPointDialog",["CometCardedDialogLoadingStateLegacy.react","GroupsCometMembershipQuestionsDialog.entrypoint","GroupsCometParticipationQuestionsDialog.entrypoint","GroupsCometParticipationQuestionsDialogFbts","react","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=a.groupID;a=a.useMQsInForum;a=a===void 0?!1:a;return c("useCometEntryPointDialog")(a?c("GroupsCometMembershipQuestionsDialog.entrypoint"):c("GroupsCometParticipationQuestionsDialog.entrypoint"),{groupID:b},void 0,function(a){return i.jsx(c("CometCardedDialogLoadingStateLegacy.react"),{onClose:a,title:d("GroupsCometParticipationQuestionsDialogFbts").participationQuestionsDialogTitle,withCloseButton:!0})})}g["default"]=a}),98);
__d("GroupsCometFeatureDetailViewDialog.entrypoint",["GroupsCometFeatureDetailViewDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeProps;var b=a.featureID;a=a.groupID;return{queries:{queryReference:{parameters:c("GroupsCometFeatureDetailViewDialogQuery$Parameters"),variables:{featureID:b,groupID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupsCometFeatureDetailViewDialog.react").__setRef("GroupsCometFeatureDetailViewDialog.entrypoint")};g["default"]=a}),98);
__d("mapMap",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){var c=new Map();a.forEach(function(a,d){c.set(d,b(a,d))});return c}f["default"]=a}),66);
__d("GroupsCometEndOfFeedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6254718261226056"}),null);
__d("GroupsCometNewMemberGreetingDialogRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6417315111729375"}),null);
__d("mapMapToArray",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){var c=[],d=0;for(var e=a,f=Array.isArray(e),g=0,e=f?e:e[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var h;if(f){if(g>=e.length)break;h=e[g++]}else{g=e.next();if(g.done)break;h=g.value}h=h;var i=h[0];h=h[1];c.push(b(h,i,d,a));d++}return c}f["default"]=a}),66);/*FB_PKG_DELIM*/
__d("GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group",selections:[{alias:"off_plat_comet_crawlability_gk",args:[{kind:"Literal",name:"gk_name",value:"groups_off_platform_distribution_comet_crawability"}],concreteType:"EntGKCheck",kind:"LinkedField",name:"gk_check",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"passes_gk",storageKey:null}],storageKey:'gk_check(gk_name:"groups_off_platform_distribution_comet_crawability")'}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("CrisisCometLogging",["react","requireDeferred","useSinglePartialViewImpression"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;e=b.createContext;var j=b.useCallback,k=b.useContext,l=b.useMemo,m=c("requireDeferred")("CrisisClickUnitFalcoEvent").__setRef("CrisisCometLogging"),n=c("requireDeferred")("CrisisToolViewPageFalcoEvent").__setRef("CrisisCometLogging"),o=c("requireDeferred")("CrisisViewModuleFalcoEvent").__setRef("CrisisCometLogging"),p=c("requireDeferred")("CrisisViewUnitFalcoEvent").__setRef("CrisisCometLogging"),q=e();function r(){var a=k(q),b=function(b){m.onReady(function(c){c.log(function(){return{crisis_id:a==null?void 0:a.crisis_id,extra_data:babelHelpers["extends"]({},a,b)}})})},d=j(function(b){n.onReady(function(c){c.log(function(){return{crisis_id:a==null?void 0:a.crisis_id,extra_data:babelHelpers["extends"]({},a,b)}})})},[a]),e=function(b){b===void 0&&(b={});var d=r(),a=d.logViewedUnit;d=j(function(){return a(b)},[a,b]);return c("useSinglePartialViewImpression")({onImpressionStart:d})},f=function(b){b===void 0&&(b={});var d=r(),a=d.logViewedModule;d=j(function(){return a(b)},[a,b]);return c("useSinglePartialViewImpression")({onImpressionStart:d})},g=j(function(b){p.onReady(function(c){c.log(function(){return{crisis_id:a==null?void 0:a.crisis_id,extra_data:babelHelpers["extends"]({},a,b)}})})},[a]),h=j(function(b){o.onReady(function(c){c.log(function(){return{crisis_id:a==null?void 0:a.crisis_id,extra_data:babelHelpers["extends"]({},a,b)}})})},[a]);return{logClick:b,loggingContextData:a,logViewedModule:h,logViewedPage:d,logViewedUnit:g,useCrisisViewedModuleLogging:f,useCrisisViewedUnitLogging:e}}function a(a,b){return function(c){var d=k(q),e=b&&b(c),f=l(function(){return babelHelpers["extends"]({},d,e)},[d,e]);return i.jsx(q.Provider,{value:f,children:i.jsx(a,babelHelpers["extends"]({},c))})}}g.useCrisisLogging=r;g.withCrisisLoggingProvider=a}),98);
__d("GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList.react",["CometFeedInfiniteScrollSuspenseList.react","CometRelay","GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group.graphql","gkx","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||(i=d("react")),k=i.useMemo;function a(a){var e=a.group$key,f=babelHelpers.objectWithoutPropertiesLoose(a,["group$key"]);a=d("CometRelay").useFragment(h!==void 0?h:h=b("GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group.graphql"),e);var g=(a=a==null?void 0:(e=a.off_plat_comet_crawlability_gk)==null?void 0:e.passes_gk)!=null?a:!1;e=k(function(){return!c("gkx")("1779508")||!g?f:babelHelpers["extends"]({},f,{incrementalRendering:!1,waitOnScrollIntent:!1})},[g,f]);return j.jsx(c("CometFeedInfiniteScrollSuspenseList.react"),babelHelpers["extends"]({},e))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometNewMemberConsumptionDialogRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="23889938297317262"}),null);